// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SealGame.Data;

#nullable disable

namespace SealGame.Data.Migrations
{
    [DbContext(typeof(DatabaseTaskDbContext))]
    [Migration("20241128141129_Tere1")]
    partial class Tere1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SealGame.Core.Domain.Seal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cleanliness")
                        .HasColumnType("int");

                    b.Property<int>("Enrichment")
                        .HasColumnType("int");

                    b.Property<int>("Happiness")
                        .HasColumnType("int");

                    b.Property<int>("Hunger")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Seals");
                });

            modelBuilder.Entity("SealGame.Core.Domain.SealSpecies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxCleanliness")
                        .HasColumnType("int");

                    b.Property<int>("MaxEnrichment")
                        .HasColumnType("int");

                    b.Property<int>("MaxHappiness")
                        .HasColumnType("int");

                    b.Property<int>("MaxHunger")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SealSpecies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "imelik",
                            MaxCleanliness = 100,
                            MaxEnrichment = 80,
                            MaxHappiness = 100,
                            MaxHunger = 50,
                            Name = "Weddell Seal"
                        },
                        new
                        {
                            Id = 2,
                            Description = "rõngik",
                            MaxCleanliness = 95,
                            MaxEnrichment = 85,
                            MaxHappiness = 90,
                            MaxHunger = 60,
                            Name = "Ringed Seal"
                        },
                        new
                        {
                            Id = 3,
                            Description = "tavaline",
                            MaxCleanliness = 100,
                            MaxEnrichment = 90,
                            MaxHappiness = 95,
                            MaxHunger = 55,
                            Name = "Harbor Seal"
                        });
                });

            modelBuilder.Entity("SealGame.Core.Dto.FileToDatabaseDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SealId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SealId");

                    b.ToTable("FileToDatabaseDto");
                });

            modelBuilder.Entity("SealGame.Core.Domain.Seal", b =>
                {
                    b.HasOne("SealGame.Core.Domain.SealSpecies", "Species")
                        .WithMany("Seals")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("SealGame.Core.Dto.FileToDatabaseDto", b =>
                {
                    b.HasOne("SealGame.Core.Domain.Seal", "Seal")
                        .WithMany()
                        .HasForeignKey("SealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seal");
                });

            modelBuilder.Entity("SealGame.Core.Domain.SealSpecies", b =>
                {
                    b.Navigation("Seals");
                });
#pragma warning restore 612, 618
        }
    }
}
